version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  coworking-server:
    image: franksal/coworkingapp-server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  coworking-app:
    image: franksal/coworkingapp-app
    ports:
      - "80:80"
    depends_on:
      - postgres
      - coworking-server
volumes:
  db_data:
